import React, { useState } from "react";
import { useStore, Notification } from "../lib/store";

export default function NotificationCenter() {
  const { notifications, dismissNotification } = useStore();
  const [previewContent, setPreviewContent] = useState<string | null>(null);

  if (notifications.length === 0 && !previewContent) return null;

  return (
    <>
      {/* Toast Stack */}
      <div className="fixed bottom-8 right-8 z-[300] flex flex-col gap-4 pointer-events-none">
        {notifications.map((n) => (
          <div 
            key={n.id} 
            className="w-80 md:w-96 bg-brand-card/90 backdrop-blur-xl border border-white/10 p-5 rounded-3xl shadow-glow animate-in slide-in-from-right duration-500 pointer-events-auto group"
          >
            <div className="flex justify-between items-start mb-2">
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 rounded-full bg-brand-primary/20 flex items-center justify-center text-brand-primary">
                  <span className="material-symbols-outlined text-sm filled-icon">mail</span>
                </div>
                <h4 className="text-[11px] font-black text-white uppercase tracking-widest">{n.title}</h4>
              </div>
              <button 
                onClick={() => dismissNotification(n.id)}
                className="text-gray-600 hover:text-white transition-colors"
              >
                <span className="material-symbols-outlined text-sm">close</span>
              </button>
            </div>
            
            <p className="text-gray-400 text-xs font-medium mb-4 leading-relaxed">
              {n.message}
            </p>
            
            <div className="flex items-center justify-between border-t border-white/5 pt-3">
              <button 
                onClick={() => setPreviewContent(n.content || null)}
                className="text-[9px] font-black text-brand-primary uppercase tracking-[0.3em] hover:underline"
              >
                View Protocol Comms
              </button>
              <span className="text-[8px] text-gray-700 font-bold uppercase tracking-widest">
                AI Synthesis Complete
              </span>
            </div>
          </div>
        ))}
      </div>

      {/* Draft Preview Overlay */}
      {previewContent && (
        <div className="fixed inset-0 z-[400] bg-black/95 backdrop-blur-2xl flex items-center justify-center p-6 animate-in fade-in duration-500">
          <div className="relative w-full max-w-3xl bg-brand-card border border-white/10 rounded-[3rem] p-12 overflow-hidden shadow-2xl animate-in zoom-in-95 duration-500">
            {/* Terminal Glow */}
            <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-transparent via-brand-primary to-transparent opacity-50"></div>
            
            <div className="flex justify-between items-center mb-10">
              <div className="flex items-center gap-4">
                <div className="w-10 h-10 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center text-brand-primary">
                  <span className="material-symbols-outlined">description</span>
                </div>
                <div>
                  <h3 className="text-white font-bold tracking-tight">Email Dispatch Protocol</h3>
                  <p className="text-[9px] text-gray-500 font-black uppercase tracking-[0.4em]">Synthetic Transmission Log</p>
                </div>
              </div>
              <button 
                onClick={() => setPreviewContent(null)}
                className="p-3 bg-white/5 border border-white/10 rounded-full text-gray-500 hover:text-white transition-colors"
              >
                <span className="material-symbols-outlined">close</span>
              </button>
            </div>

            <div className="bg-black/60 rounded-2xl p-8 border border-white/5 h-[50vh] overflow-y-auto no-scrollbar font-mono text-sm leading-relaxed text-gray-300">
               <pre className="whitespace-pre-wrap">{previewContent}</pre>
            </div>

            <div className="mt-10 flex justify-between items-center">
              <p className="text-[10px] text-gray-600 font-black uppercase tracking-[0.2em]">Generated by SB Tech Solution Intelligence Protocol</p>
              <button 
                onClick={() => setPreviewContent(null)}
                className="bg-white text-black font-black px-10 py-4 rounded-xl text-[10px] uppercase tracking-[0.4em] hover:opacity-80 transition-all shadow-2xl"
              >
                Acknowledge
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}